# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

variables:
  KeyVaultName: <keyvaultname>
  azureSubscription: <ServiceConnection>
  SourceDataFactoryName : <Source Data Factory name from which code is published>
  DeployDataFactoryName : <Target Data Factory Name>
  DeploymentResourceGroupName : <Target Resource Group Name>
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
